# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-07 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_field', models.CharField(max_length=100)),
                ('comapany_country', models.CharField(blank=True, max_length=100, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_contact', models.PositiveIntegerField()),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_description', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.CharField(choices=[('BS', 'Business Development (Sales)'), ('WD', 'Web Development'), ('GD', 'Graphic Design'), ('CW', 'Content Writing'), ('MAD', 'Mobile App Development'), ('O', 'Operations'), ('SMM', 'Social Media Marketing'), ('M', 'Marketing'), ('DM', 'Digital Marketing'), ('HR', 'Human Resources (HR)'), ('LLE', 'Law/ Legal'), ('CA', 'Campus Ambassador')], max_length=100)),
                ('job_type', models.CharField(choices=[('R', 'Regular (In-office/On-field)'), ('WH', 'Work From Home')], max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_vacancy', models.PositiveIntegerField(blank=True, null=True)),
                ('date_from', models.DateField()),
                ('date_till', models.DateField()),
                ('job_description', models.CharField(max_length=400)),
                ('salary', models.PositiveIntegerField()),
                ('perks', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
