# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20181113_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
