# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20181113_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
