# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20181113_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_det', to=settings.AUTH_USER_MODEL),
        ),
    ]
