# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20181113_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
