# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-26 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='awards',
            new_name='Award',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bachelor_result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='diploma_result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
