# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0005_auto_20181107_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
