# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-07 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_usermodel_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certification_organization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
