# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-21 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0018_auto_20181122_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='applied_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
