# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-26 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0019_jobs_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Reviewed', 'Reviewed'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bachelor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='tenth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='twelfth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
