# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-26 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0020_auto_20181126_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bachelor_program',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bachelor_stream',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
