# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-26 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0023_auto_20181126_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='bachelor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='diploma_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='tenth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='twelfth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
