# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-26 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0024_auto_20181126_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='bachelor_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='diploma_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='tenth_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='twelfth_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
